// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqnUOT7G6sFvWe4lOrjlqK_tOEKCnWHM',
    appId: '1:132257993419:android:2521ca0cccb0a1c540014e',
    messagingSenderId: '132257993419',
    projectId: 'udemy-chat-886af',
    storageBucket: 'udemy-chat-886af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLbsh6Et0QMzGANJZTt6eEK7NFOPJeF0',
    appId: '1:132257993419:ios:b2490ca3d6dc488e40014e',
    messagingSenderId: '132257993419',
    projectId: 'udemy-chat-886af',
    storageBucket: 'udemy-chat-886af.appspot.com',
    iosClientId: '132257993419-90cm3tevl1ppk9200ha1b2kd46tdh4i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.udem',
  );
}
